name: POI-CI

# If you want to trigger this branch then change the branch name to a usable branch name
on:
  pull_request:
    branches: [master, ch3]
    paths:
      - apis/poi/**
      - .github/workflows/POI-CI.yml

  push:
    branches: [master, ch3]
    paths:
      - apis/poi/**
      - .github/workflows/POI-CI.yml

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT CURRENT REPO
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1

        #with:
        #  dotnet-version: '3.1.202'
      - name: Install dependencies
        run: dotnet restore apis/poi/web/*.csproj

      - name: .NET Build Web
        run: dotnet build --configuration Release --no-restore apis/poi/web/*.csproj

      - name: .NET Build Unit Tests
        run: dotnet build --configuration Release apis/poi/tests/UnitTests/UnitTests.csproj

      - name: .NET Test
        # The next "run" has been disable since Coveralls does not support private Repos with the free option.
        #run: dotnet test --no-restore --verbosity normal apis/poi/tests/UnitTests  /p:CollectCoverage=true /p:CoverletOutput=lcov/ /p:CoverletOutputFormat=lcov
        #The following action will execute the *.csproj solution inside the specified directory
        run: dotnet test --no-restore --verbosity normal apis/poi/tests/UnitTests
