name: POI-CI
on:
  pull_request:
    branches: [master, ch3]
    paths:
      - apis/poi/**
      - .github/workflows/POI-CI.yml

  push:
    branches: [master, ch3]
    paths:
      - apis/poi/**
      - .github/workflows/POI-CI.yml

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT CURRENT REPO
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1

      - name: Install dependencies
        run: dotnet restore apis/poi/web/*.csproj

      - name: .NET Build Web
        run: dotnet build --configuration Release --no-restore apis/poi/web/*.csproj

      - name: .NET Build Unit Tests
        run: dotnet build --configuration Release apis/poi/tests/UnitTests/UnitTests.csproj

      - name: .NET Test
        run: dotnet test --no-restore --verbosity normal apis/poi/tests/UnitTests
