name: POI-CD
on:
  push:
    branches: [master, ch4]
    paths:
      - apis/poi/**
      - .github/workflows/POI-CD.yml

# Variables used in the jobs
env:
  registry: openhack9iw8z9x2acr.azurecr.io
  repository: devopsoh/api-poi
  docker_path: apis/poi/web

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        run: docker login $registry -u ${{ secrets.ACR_USER }} -p ${{ secrets.ACR_KEY }}

      - name: Docker build
        run: docker build -t $registry/$repository:${{github.run_id}} --build-arg build_version=${{github.run_id}} $docker_path

      - name: Docker Push
        run: docker push $registry/$repository:${{github.run_id}}

      - uses: nashmaniac/create-issue-action@v1.1
        if: failure()
        name: Create Issue Action
        with:
          title: Build Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: worflow-failed
          body: |
            ${{ github.workflow }} Workflow failed for commit ${{github.sha}}
            Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
