name: trips-CI
on:
  pull_request:
    branches: [master, ch3]
    paths:
      - apis/trips/**
      - .github/workflows/trips-CI.yml

  push:
    branches: [master, ch3]
    paths:
      - apis/trips/**
      - .github/workflows/trips-CI.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: dependencies
        run: go get ./apis/trips/tripsgo/

      - name: Build
        run: go build ./apis/trips/tripsgo/

      - name: Test
        run: go test ./apis/trips/tripsgo/ -run Unit
