name: trips-CI
on:
  pull_request:
    branches: [master, ch3]
    paths:
      - apis/trips/**
      - .github/workflows/trips-CI.yml

  push:
    branches: [master, ch3]
    paths:
      - apis/trips/**
      - .github/workflows/trips-CI.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.12

      - name: Switch Directory
        run: |
          cd ./apis
          ls

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./tests/
