name: trips-CI
on:
  pull_request:
    branches: [master, ch3]
    paths:
      - apis/trips/**
      - .github/workflows/trips-CI.yml

  push:
    branches: [master, ch3]
    paths:
      - apis/trips/**
      - .github/workflows/trips-CI.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: download dependencies
        run: go get ./apis/trips/...

      - name: Build
        run: go build -v ./apis/trips/...

      - name: Test
        run: go test ./tripgo -run Unit
