name: userprofile-CI
on:
  pull_request:
    branches: [master, ch3]
    paths:
      - apis/userprofile/**
      - .github/workflows/userprofile-CI.yml

  push:
    branches: [master, ch3]
    paths:
      - apis/userprofile/**
      - .github/workflows/userprofile-CI.yml

defaults:
  run:
    working-directory: apis/userprofile/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 8.x
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
