name: user-java-CI
on:
  pull_request:
    branches: [master, ch3]
    paths:
      - apis/user-java/**
      - .github/workflows/user-java-CI.yml

  push:
    branches: [master, ch3]
    paths:
      - apis/user-java/**
      - .github/workflows/user-java-CI.yml

defaults:
  run:
    working-directory: apis/user-java/

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - uses: actions/github-script@4
        if: failure()
        with:
          script: |
            let body = "${{ env.build_name }} Worflow Failure \n Build Number:
            ${{ github.run_number }} \n Build Log: https://github.com/${{
            github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{
            github.sha }}](https://github.com/${{ github.repository
            }}/commit/${{ github.sha }}) \n";
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
              body: body
            });
