name: user-java-CI
on:
  pull_request:
    branches: [master, ch3]
    paths:
      - apis/user-java/**
      - .github/workflows/user-java-CI.yml

  push:
    branches: [master, ch3]
    paths:
      - apis/user-java/**
      - .github/workflows/user-java-CI.yml

defaults:
  run:
    working-directory: apis/user-java/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: run tests
        run: mvn test
